/*
 * Dio_Cfg.c
 *
 *  Created on: Sep 13, 2022
 *      Author: 10
 */

#include "Dio_Cfg.h"
#include "Dio.h"

Dio_Pin_Config Dio_Cfg_Pins[PIN_COUNT] = {
		{PORT_A,PIN_4,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_5,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_6,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_7,OUTPUT,PULLUP_OFF},
		{PORT_B,PIN_0,INPUT,PULLUP_OFF},
		{PORT_B,PIN_1,OUTPUT,PULLUP_OFF},
		{PORT_B,PIN_2,OUTPUT,PULLUP_OFF},
		{PORT_B,PIN_3,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_0,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_1,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_2,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_3,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_4,INPUT,PULLUP_ON},
		{PORT_C,PIN_5,INPUT,PULLUP_ON},
		{PORT_C,PIN_6,INPUT,PULLUP_ON},
		{PORT_C,PIN_7,INPUT,PULLUP_ON},
		{PORT_D,PIN_4,OUTPUT,PULLUP_OFF},
		{PORT_D,PIN_2,INPUT,PULLUP_OFF}
};


